name: fast_trivia
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  json_rest_server: ^1.5.10
  flutter_riverpod: ^2.3.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
