name: fast_trivia
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dio: ^5.3.2
  enum_to_string: ^2.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_riverpod: ^2.3.7
  flutter_staggered_animations: ^1.1.1
  flutter_swipe_button: ^2.1.1+1
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.8
  html_character_entities: ^1.0.0+1
  json_rest_server: 1.0.10
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
